FROM node:24

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Define o timezone
ENV TZ=America/Fortaleza

# Expõe a porta 3000
EXPOSE 3000

# Instala as dependências e inicia a aplicação em modo desenvolvimento
CMD npm install && npm run dev